#!/usr/bin/env python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from zipfile import ZipFile
import os, os.path, sys
scriptdir = os.path.dirname(os.path.abspath(sys.argv[0]))
extensionname = open(
    os.path.join(scriptdir, 'extensionname.txt')).readlines()[0].rstrip('\n')
with ZipFile(extensionname, 'w') as helloworldzip:
    os.chdir(scriptdir)
    for root, dirs, files in os.walk('.'):
        for name in files:
            if not name == extensionname:
                helloworldzip.write(os.path.join(root, name))
